#!/bin/bash
REPO=$HOME/.config/vscode

mkdir -p $HOME/.config/Code/User

# Copy VSCode settings and snippets into dev container
ln -sf $REPO/settings.json $HOME/.config/Code/User/settings.json
ln -sf $REPO/keybindings.json $HOME/.config/Code/User/keybindings.json
ln -sf $REPO/snippets $HOME/.config/Code/User/snippets

# Symlink your startup script
ln -sf $REPO/os/linux/zshrc ~/.zshrc

# Install debian libraries
apt-get install -y zsh jq

# Switch shell to zsh
# echo "exec zsh" >> $HOME/.bashrc
# Invoke zsh using interactive mode (loads ~/.zshrc) to run a single command
# The command is `rbenv exec ruby`, which automatically sets all relevant environment variables and selects the
# specified Ruby version
# We then print the activated environment as JSON. We read that JSON from the NodeJS process to insert the needed
# environment variables in order to run Ruby correctly
# echo /bin/zsh -ic 'rbenv exec ruby -rjson -e "puts JSON.dump(ENV.to_h)"' >> $HOME/.bashrc

# echo "if [[ -n \$ZSH_INIT_COMMAND ]]; then
#   eval "\$ZSH_INIT_COMMAND"
# fi
# " >> $HOME/.bashrc

# Install pure-prompt
npm install --global pure-prompt
