#!/bin/bash
REPO=$HOME/.config/vscode

mkdir -p $HOME/.config/Code/User

# Copy VSCode settings and snippets into dev container
ln -sf $REPO/settings.json $HOME/.config/Code/User/settings.json
ln -sf $REPO/keybindings.json $HOME/.config/Code/User/keybindings.json
ln -sf $REPO/snippets $HOME/.config/Code/User/snippets

# Symlink your startup script
ln -sf $REPO/os/linux/zshrc ~/.zshrc

# Install debian libraries
apt-get install -y zsh jq vim

# Install pure-prompt
npm install --global pure-prompt

# Clone vimrc
git clone https://github.com/callahanrts/vim-config $HOME/.config/vim
# Put the .vimrc in place
ln -sf $HOME/.config/vim/vimrc $HOME/.vimrc

# Install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# Install vim-plug plugins
yes | vim +'PlugInstall --sync' +qa
