#!/bin/bash
REPO=$HOME/.config/vscode

mkdir -p $HOME/.config/Code/User

# Copy VSCode settings and snippets into dev container
ln -sf $REPO/settings.json $HOME/.config/Code/User/settings.json
ln -sf $REPO/keybindings.json $HOME/.config/Code/User/keybindings.json
ln -sf $REPO/snippets $HOME/.config/Code/User/snippets

# Symlink your startup script
ln -sf $REPO/os/linux/zshrc ~/.zshrc

# Install debian libraries
sudo apt update
apt-get install -y zsh jq vim gpg

# Install eza
sudo mkdir -p /etc/apt/keyrings
wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
sudo apt update
sudo apt install -y eza

# Install pure-prompt
npm install --global pure-prompt

# Clone vimrc
git clone https://github.com/callahanrts/vim-config $HOME/.config/vim
# Put the .vimrc in place
ln -sf $HOME/.config/vim/vimrc $HOME/.vimrc

# Install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# Install vim-plug plugins
yes | vim +'PlugInstall --sync' +qa

# Clone DS script
git clone https://github.com/sendcutsend/scsdev $HOME/.config/sendcutsend/scsdev
