# Load zsh prompt
autoload -U promptinit; promptinit
prompt pure
export PURE_PROMPT_SYMBOL=" ❯"

# Aliases
alias ls='eza'
alias l='ls -al'
alias uncommit='git reset --soft HEAD\^'
export EDITOR='vim'

# Misc. functions
function gbranch() {
  size="${1:-8}"
  git for-each-ref --sort='-committerdate' --format='%(refname)%09%(committerdate)' refs/heads | sed -e 's-refs/heads/--' | head -n $size
}

function grefresh() {
  curbranch=$(git branch | grep "*")
  branch=${curbranch:2}
  git reset --hard origin/$branch
  git pull
}

# Make SCSDev executables available
export PATH="$PATH:$HOME/.config/sendcutsend/scsdev/bin"
